#! /bin/bash
if [[ $# -gt 1 ]];
then
	echo -e "[\e[0;31merror\e[1;0m] arguments of ssh-key name exceeds more than \e[1;31mone\e[0m!"
	return;
fi
ssh_name=$1;
file=~/.ssh/$ssh_name;
function ssh_init() {
	# if [[ $(ssh-add -l) == "The agent has no identities." ]]
	# then
	if [[ -f $file ]];
	then
		echo -e "\e[0m[\e[1;33madd\e[0m] Adding identity -- \e[1;33m$ssh_name\e[0m";
		echo -e "[\e[1;33mssh-agent\e[0m] \c";
		ssh-add $file;
	fi
	# fi
	echo -e "\e[0m================================================================================";
	echo -e "\e[1;32mACTIVE IDENTITIES\e[1;33m";
	ssh-add -l;
	echo -e "\e[0m================================================================================";
}
if [[ -f $file ]];
then
	echo -e "[\e[1;32mgood\e[0m] ssh-key name argument exists";
	if [[ $(ps ax | grep -w "ssh-agent" | grep -v "grep" | wc -l) -gt 0 ]]; 
	then
		echo -e "[\e[1;34mnotice\e[0m] ssh-agent is already running in system: \e[1;34mAgent pid $SSH_AGENT_PID ";
	else
		echo -e "\e[0m[\e[1;34mcreated\e[0m] no ssh-agent process currently running in terminal, created new instance \e[1;34m\c";
		test -r ~/.ssh-agent && \
			eval "$(<~/.ssh-agent)" >/dev/null
		ssh-add -l &>/dev/null
		if [[ $? == 2 ]]; 
		then
			(umask 066; ssh-agent > ~/.ssh-agent)
			eval "$(<~/.ssh-agent)" >/dev/null
		fi
		source ~/.ssh-agent;
		echo -e "\e[0m[\e[1;32madded\e[0m] Added ssh session to current terminal";
	fi
	ssh_init
elif [[ $( ps ax | grep -w "ssh-agent" | grep -v "grep" | wc -l) -eq 1 && -z $1 ]];
then
	if [[ -n $SSH_AGENT_PID ]];
	then
		echo -e "[\e[1;34mnotice\e[0m] An ssh-agent process is \e[1;34malready\e[0m added to to current terminal with \e[1;34mPID PROCESS $SSH_AGENT_PID\e[0m.";
		return;
	else
		echo -e "[\e[1;32mnotice\e[0m] no ssh-agent is added to current terminal, yet there is an \e[1;32malready\e[0m existing session in the system";
		echo -e "[\e[1;34madded\e[0m] ssh-agent session added to terminal. \e[1;36m --- \e[1;34m\c \n"
		source ~/.ssh-agent;
		ssh_init
	fi
else
	if [[ $# -eq 0 ]]; 
	then
		echo -e "[\e[0;31merror\e[0m] ssh-key name argument is \e[1;31mnone\e[0m! And pre-existing ssh-agent processes are \e[1;31mnot\e[0m found or are found to be \e[1;31mmore\e[0m than one!"
		echo -e "[\e[1;32mhint\e[0m] If there are \e[1;32mmore\e[0m than one ssh-agents, please kill the pre-existing ssh-agent process.";
		return;
	else
		echo -e "[\e[0;31merror\e[0m] ssh-key does not exists!"
		echo -e "=================="
		echo -e "AVAILABLE SSH-KEYS\e[1;33m"
		ls -A ~/.ssh/ | grep -v '.pub\|known_hosts\|.sock\|ssh-agent'
		echo -e "\e[0m=================="
	fi
fi
